name: Build LaTeX Monograph

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up LaTeX
        uses: dante-ev/latex-action@v2
        with:
          root_file: src/main.tex
          compiler: latexmk
          args: "-pdf -interaction=nonstopmode -halt-on-error"

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: monograph-pdf
          path: src/main.pdf

      - name: Lint TeX sources
        run: |
          sudo apt-get update
          sudo apt-get install -y chktex
          chktex -q -n22 -n30 -n46 -I0 -v0 src/**/*.tex || true
